### ISSUE TITLE
test_run_without_subcommand(TC_CLI_Command) failed

### ISSUE THREAD

**Issue by parjong** [parjong/ruby-cli#2]
NameError: undefined local variable or method `opts' for #<CLI::Command:0x00000001a292d8>
    /home/parjong/libraries/ruby/cli/lib/cli.rb:36:in `run'
    /home/parjong/libraries/ruby/cli/test/test_cli.rb:45:in `test_run_without_subcommand'

**Comment by parjong** [comment]
Another test failure

test_run_without_subcommand(TC_CLI_Command):
NoMethodError: undefined method `[]=' for nil:NilClass
    /home/parjong/libraries/ruby/cli/test/test_cli.rb:41:in `block (2 levels) in test_run_without_subcommand'
    /home/parjong/libraries/ruby/cli/lib/cli.rb:38:in `call'
    /home/parjong/libraries/ruby/cli/lib/cli.rb:38:in `block in run'
    /home/parjong/libraries/ruby/cli/lib/cli.rb:38:in `each'
    /home/parjong/libraries/ruby/cli/lib/cli.rb:38:in `run'
    /home/parjong/libraries/ruby/cli/test/test_cli.rb:45:in `test_run_without_subcommand'
